services:
  - type: web
    name: job-scrapper-scrapers
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    rootDir: scrapers
    envVars:
      - key: PORT
        value: "3001"

  - type: web
    name: job-scrapper-backend
    runtime: go
    plan: free
    buildCommand: go build -o main .
    startCommand: ./main
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SCRAPER_SERVICE_URL
        value: http://job-scrapper-scrapers:3001
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
