import { useState, useEffect } from "react";
import JobCard, { type Job } from "../components/JobCard";
import FilterBar from "../components/FilterBar";
import { API_BASE_URL } from "../config";
import { RefreshCw } from "lucide-react";

interface RecommendedJobsProps {
  sharedJobs: Job[];
  setSharedJobs: React.Dispatch<React.SetStateAction<Job[]>>;
  isLoaded: boolean;
  setIsLoaded: React.Dispatch<React.SetStateAction<boolean>>;
}

export default function RecommendedJobs({
  sharedJobs,
  setSharedJobs,
  isLoaded,
  setIsLoaded,
}: RecommendedJobsProps) {
  const [loading, setLoading] = useState(!isLoaded);

  const fetchJobs = async (queryString = "") => {
    if (sharedJobs.length === 0) setLoading(true);
    try {
      const endpoint = queryString
        ? `${API_BASE_URL}/jobs/filter?${queryString}&recommended=true`
        : `${API_BASE_URL}/jobs/recommended`;
      const response = await fetch(endpoint);
      const data = await response.json();
      setSharedJobs(Array.isArray(data) ? data : data.jobs || []);
      setIsLoaded(true);
    } catch (error) {
      console.error("Failed to fetch jobs:", error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!isLoaded) {
      fetchJobs();
    }
  }, [isLoaded]);

  const handleFilter = (filters: any) => {
    const params = new URLSearchParams();
    if (filters.keyword) params.append("keyword", filters.keyword);
    if (filters.location) params.append("location", filters.location);
    if (filters.minSalary) params.append("minSalary", filters.minSalary);
    if (filters.supportsAutoApply) params.append("supportsAutoApply", "true");
    fetchJobs(params.toString());
  };

  return (
    <div className="h-full w-full flex bg-[#0f0d0c] overflow-hidden text-slate-200">
      {/* Left Grid Pane: Sidebar Controls */}
      <aside className="w-80 border-r border-white/10 p-6 flex flex-col gap-6 overflow-y-auto shrink-0 bg-black/10">
        <div className="flex flex-col gap-1.5">
          <h2 className="text-xs font-bold uppercase tracking-wider text-slate-400">
            Filter Recommendations
          </h2>
          <p className="text-[11px] text-slate-500 leading-normal">
            Refine listings scoring highly against your active identity configuration.
          </p>
        </div>

        <FilterBar onFilter={handleFilter} />
      </aside>

      {/* Right Grid Pane: Full Screen Table Matrix */}
      <main className="flex-1 flex flex-col h-full overflow-hidden">
        <header className="px-8 py-5 border-b border-white/10 flex items-center justify-between shrink-0 bg-black/5">
          <div>
            <h1 className="text-lg font-bold text-slate-100 tracking-wide bg-clip-text text-transparent bg-gradient-to-r from-cyan-400 to-violet-400">
              Recommended Roles
            </h1>
            <p className="text-xs text-slate-400">
              Jobs with matching confidence scores generated by Gemini AI
            </p>
          </div>
          <div className="text-xs font-mono text-slate-400 bg-white/5 border border-white/10 px-3 py-1 rounded-lg">
            {sharedJobs.length} aligned records
          </div>
        </header>

        {/* Matrix Header Row */}
        <div className="grid grid-cols-12 gap-4 px-8 py-3 bg-white/5 border-b border-white/10 text-[10px] font-bold uppercase tracking-widest text-slate-400 shrink-0">
          <div className="col-span-4">Role / Organization</div>
          <div className="col-span-3">Location & Base Salary</div>
          <div className="col-span-2">Alignment</div>
          <div className="col-span-2">Source</div>
          <div className="col-span-1 text-right">Actions</div>
        </div>

        {/* Matrix List Feed */}
        <div className="flex-1 overflow-y-auto no-scrollbar divide-y divide-white/10 bg-black/5">
          {loading ? (
            <div className="flex flex-col items-center justify-center h-full gap-4">
              <RefreshCw className="w-6 h-6 animate-spin text-cyan-400" />
              <span className="text-sm font-medium text-slate-400">
                Analyzing match alignment metrics...
              </span>
            </div>
          ) : sharedJobs.length > 0 ? (
            sharedJobs.map((job) => <JobCard key={job.id} job={job} />)
          ) : (
            <div className="flex flex-col items-center justify-center h-64 text-center px-6">
              <span className="text-sm font-medium text-slate-400">
                No high-confidence matches found. Try updating your profile details.
              </span>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
